/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista_g32;

import Nutricionista_G32_accesoDatos.Comida_Data;
import Nutricionista_G32_entidades.Comida;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuComida extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    public MenuComida() {
        initComponents();

        armarCabecera();
        jBmodificar.setEnabled(false);
        jBguardar.setEnabled(false);
        jTnombre.setEnabled(false);
        jTidComida.setEnabled(false);
        jTcalorias.setEnabled(false);
        jTableComidas.setEnabled(false);
        jTbuscador.setEnabled(false);
        jTdetalle.setEnabled(false);
        jBeliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTidComida = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTcalorias = new javax.swing.JTextField();
        jRBnuevo = new javax.swing.JRadioButton();
        jRBbuscar = new javax.swing.JRadioButton();
        jBmodificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdetalle = new javax.swing.JTextArea();
        jTbuscador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableComidas = new javax.swing.JTable();
        jBguardar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("COMIDAS");
        setPreferredSize(new java.awt.Dimension(1050, 398));

        jLabel1.setText("Identificador");

        jLabel2.setText("Nombre");

        jLabel3.setText("Calorias");

        jLabel4.setText("Detalle");

        jTcalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcaloriasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBnuevo);
        jRBnuevo.setText("NUEVO");
        jRBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBnuevoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBbuscar);
        jRBbuscar.setText("BUSCAR");
        jRBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBbuscarActionPerformed(evt);
            }
        });

        jBmodificar.setText("MODIFICAR");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jTdetalle.setColumns(20);
        jTdetalle.setRows(5);
        jScrollPane1.setViewportView(jTdetalle);

        jTbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscadorActionPerformed(evt);
            }
        });
        jTbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbuscadorKeyReleased(evt);
            }
        });

        jLabel5.setText("Buscador");

        jTableComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableComidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComidasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableComidas);

        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBeliminar.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jBmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 110, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTidComida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRBnuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBbuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jBguardar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jTbuscador))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTidComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRBnuevo)
                        .addComponent(jTbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRBbuscar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBmodificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBeliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(jBguardar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcaloriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcaloriasActionPerformed

    private void jTbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscadorActionPerformed

    private void jRBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBnuevoActionPerformed
        borrarFilas();
        jBmodificar.setEnabled(false);
        jBguardar.setEnabled(true);
        jTnombre.setEnabled(true);
        jTidComida.setEnabled(false);
        jTcalorias.setEnabled(true);
        jTableComidas.setEnabled(false);
        jTbuscador.setEnabled(false);
        jTdetalle.setEnabled(true);
        jBeliminar.setEnabled(false);
        jTbuscador.setText("");
        jTidComida.setText("");
        jTnombre.setText("");
        jTcalorias.setText("");
        jTdetalle.setText("");

    }//GEN-LAST:event_jRBnuevoActionPerformed

    private void jRBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBbuscarActionPerformed
        borrarFilas();
        jBmodificar.setEnabled(false);
        jBguardar.setEnabled(false);
        jTnombre.setEnabled(false);
        jTnombre.setText("");
        jTidComida.setEnabled(false);
        jTidComida.setText("");
        jTcalorias.setEnabled(false);
        jTcalorias.setText("");
        jTableComidas.setEnabled(true);
        jTbuscador.setEnabled(true);
        jTbuscador.setText("");
        jTdetalle.setEnabled(false);
        jTdetalle.setText("");
    }//GEN-LAST:event_jRBbuscarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        try {
            if (jTnombre.getText().isEmpty() || jTcalorias.getText().isEmpty() || jTdetalle.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "NINGUN CAMPO PUEDE ESTAR VACÍO");
            } else if (Integer.parseInt(jTcalorias.getText()) < 0 || Integer.parseInt(jTcalorias.getText()) >= 3000) {
                JOptionPane.showMessageDialog(null, "EL VALOR DE LAS CALORÍAS DEBE SER ENTRE 0 Y 3000");
            } else {
                Comida comida = new Comida(jTnombre.getText(), jTdetalle.getText(), Integer.parseInt(jTcalorias.getText()), true);
                Comida_Data cD = new Comida_Data();
                cD.guardarComida(comida);

                jTnombre.setText("");
                jTidComida.setText("");
                jTcalorias.setText("");
                jTdetalle.setText("");

            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR UN NÚMERO VÁLIDO PARA CALORÍAS");
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jTbuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscadorKeyReleased
        borrarFilas();
        Comida_Data cD = new Comida_Data();
        for (Comida comid : cD.listarComidas()) {

            if (comid.getNombre_comida().toUpperCase().startsWith(jTbuscador.getText().toUpperCase())) {

                modelo.addRow(new Object[]{
                    comid.getId_comida(),
                    comid.getNombre_comida(),
                    comid.getCalorias_comida(),
                    comid.getDetalle_comida(),});
            }
        }
    }//GEN-LAST:event_jTbuscadorKeyReleased

    private void jTableComidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComidasMouseClicked
        int filaSelec = jTableComidas.getSelectedRow();

        if (filaSelec != -1) {
            jTnombre.setEnabled(true);
            jTcalorias.setEnabled(true);
            jTdetalle.setEnabled(true);
            jTidComida.setText(jTableComidas.getValueAt(filaSelec, 0) + "");
            jTnombre.setText(jTableComidas.getValueAt(filaSelec, 1) + "");
            jTcalorias.setText(jTableComidas.getValueAt(filaSelec, 2) + "");
            jTdetalle.setText(jTableComidas.getValueAt(filaSelec, 3) + "");
            jBmodificar.setEnabled(true);

        }
    }//GEN-LAST:event_jTableComidasMouseClicked

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        int id = Integer.parseInt(jTidComida.getText());
        String nombre = jTnombre.getText();
        String detalle = jTdetalle.getText();
        int calorias = Integer.parseInt(jTcalorias.getText());

        Comida comida = new Comida(id, nombre, detalle, calorias, true);
        Comida_Data cD = new Comida_Data ();
        cD.modificarComida(comida);
        
         borrarFilas();
        jBmodificar.setEnabled(false);
        jBguardar.setEnabled(false);
        jTnombre.setEnabled(false);
        jTidComida.setEnabled(false);
        jTcalorias.setEnabled(false);
        jTableComidas.setEnabled(true);
        jTbuscador.setEnabled(true);
        jTdetalle.setEnabled(false);
        jTbuscador.setText("");
        jTidComida.setText("");
        jTnombre.setText("");
        jTcalorias.setText("");
        jTdetalle.setText("");
    }//GEN-LAST:event_jBmodificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRBbuscar;
    private javax.swing.JRadioButton jRBnuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableComidas;
    private javax.swing.JTextField jTbuscador;
    private javax.swing.JTextField jTcalorias;
    private javax.swing.JTextArea jTdetalle;
    private javax.swing.JTextField jTidComida;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CALORIAS");
        modelo.addColumn("DETALLE");
        jTableComidas.setModel(modelo);
    }

    private void borrarFilas() {
        int f = jTableComidas.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
